# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cs183',
                'doc_host': 'https://TesfaAsmara.github.io',
                'git_url': 'https://github.com/TesfaAsmara/cs183',
                'lib_path': 'cs183'},
  'syms': {'cs183.core': {'cs183.core.foo': ('core.html#foo', 'cs183/core.py')}}}